name: sac_pw2_vision
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+9
  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5

  firebase_ml_vision: ^0.9.3+8
  image_picker: ^0.6.5
  camera:
  path_provider:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true